# Generated by Django 3.0.8 on 2020-07-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('formatted_address', models.CharField(max_length=100)),
            ],
        ),
    ]
