# Generated by Django 3.0.8 on 2020-07-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('formatted_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
