# Generated by Django 3.0.8 on 2020-08-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together=set(),
        ),
    ]
